version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/upfluence/log
    steps:
      - checkout
      - run: go get -t ./...
      - run: go test -v ./...

workflows:
  version: 2
  all:
    jobs:
      - test
